# Generated by Django 4.2.4 on 2023-10-23 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fines',
            fields=[
                ('fine_id', models.AutoField(primary_key=True, serialize=False)),
                ('picture', models.CharField(default='png', max_length=15)),
                ('title', models.CharField()),
                ('price', models.CharField(blank=True, null=True)),
                ('text', models.CharField()),
                ('fine_status', models.CharField(default='действует', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, null=True)),
                ('password', models.CharField(blank=True, null=True)),
                ('contacts', models.CharField(blank=True, null=True)),
                ('admin_pass', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Breaches',
            fields=[
                ('breach_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('closed_date', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('formated_date', models.DateTimeField(blank=True, null=True)),
                ('breach_status', models.CharField(default='черновик', max_length=20)),
                ('moder_id', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='FFS.users')),
            ],
        ),
        migrations.CreateModel(
            name='ConfOfFines',
            fields=[
                ('cofid', models.BigAutoField(primary_key=True, serialize=False)),
                ('fine_desc', models.CharField(blank=True, max_length=400, null=True)),
                ('breach', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='FFS.breaches')),
                ('fine', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='FFS.fines')),
            ],
            options={
                'unique_together': {('fine', 'breach')},
            },
        ),
    ]
