# Generated by Django 4.2.4 on 2023-12-20 12:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FFS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='breaches',
            name='name',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='breaches',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 20, 12, 16, 11, 994833, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
