# Generated by Django 4.2.4 on 2023-11-19 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FFS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='admin_pass',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='contacts',
            field=models.CharField(blank=True, null=True),
        ),
    ]
