# Generated by Django 4.2.4 on 2023-11-22 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FFS', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='login',
            new_name='Userlogin',
        ),
    ]
