# Generated by Django 4.2.4 on 2023-12-27 10:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FFS', '0002_breaches_name_alter_breaches_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breaches',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 27, 10, 5, 58, 761906, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='fines',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
