# Generated by Django 4.2.4 on 2023-10-25 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FFS', '0003_alter_users_login_alter_users_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fines',
            name='picture',
        ),
        migrations.AddField(
            model_name='fines',
            name='picture_url',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fines',
            name='text',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fines',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
