# Generated by Django 4.2.4 on 2023-10-27 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FFS', '0004_remove_fines_picture_fines_picture_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fines',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
