# Generated by Django 4.2.4 on 2024-01-08 11:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FFS', '0004_alter_breaches_created_date_alter_fines_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breaches',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 8, 11, 46, 56, 695162, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='fines',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
