# Generated by Django 4.2.4 on 2023-10-29 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FFS', '0005_alter_fines_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fines',
            name='title',
            field=models.CharField(blank=True, max_length=70, null=True, unique=True),
        ),
    ]
